/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jardinedenhotel.view;

import com.jardinedenhotel.connection.conexionn;
import com.jardinedenhotel.controller.Encoder;
import com.jardinedenhotel.controller.Login;
import com.jardinedenhotel.model.User;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Yader Jr
 */
public class LoginForm extends javax.swing.JFrame {

    //variable para enviar datos entre interfaces
    public static String user = "";
    String pass = "";
    int intentos;
    User usuario;

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();

        setSize(800, 540);

        setResizable(false);

        setTitle("Acceso al sistema de gestión hotelera Jardin del Eden");

        setLocationRelativeTo(null);

        //this.setExtendedState(MAXIMIZED_BOTH);
        ImageIcon wallpaper = new ImageIcon("src/img/hotel2.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_fondo_login.getWidth(),
                label_fondo_login.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        label_fondo_login.setIcon(icono);

        this.repaint();

        ImageIcon icono_login = new ImageIcon("src/img/usuario4.png");
        Icon icono2 = new ImageIcon(icono_login.getImage().getScaledInstance(label_icono_login.getWidth(),
                label_icono_login.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        label_icono_login.setIcon(icono2);

        this.repaint();

        ImageIcon icono_pass = new ImageIcon("src/img/programador.png");
        Icon icono3 = new ImageIcon(icono_pass.getImage().getScaledInstance(jLabel3.getWidth(),
                jLabel3.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        jLabel3.setIcon(icono3);

        this.repaint();

        ImageIcon icono_user = new ImageIcon("src/img/padlock.png");
        Icon icono4 = new ImageIcon(icono_user.getImage().getScaledInstance(jLabel5.getWidth(),
                jLabel5.getHeight(), Image.SCALE_DEFAULT));

        //metodo setIcon para asignarle el wallpaper al label
        jLabel5.setIcon(icono4);

        this.repaint();

        setIconImage(new ImageIcon(getClass().getResource("/img/logo_hotel.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_icono_login = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        label_fondo_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(label_icono_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 150, 130));

        txt_username.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 30));

        txt_pass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 180, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesión");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 120, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 238, 30, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 308, 30, 30));

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Mostrar contraseña");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));
        getContentPane().add(label_fondo_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Encoder encoder = new Encoder();

        usuario = new User();

        Encoder encoder = new Encoder();

        user = txt_username.getText().trim();

        pass = txt_pass.getText().trim();

        String password = encoder.ecnode(pass);
//        String username = usuario.getUsername();
//        String password = usuario.getPassword();

        //encoder.ecnode(txt_pass.getText().trim());
//        Login ob1 = new Login();
//
//        if (ob1.login(user, pass, txt_username, txt_pass))
//        {
//            this.dispose();
//        }
//        boolean bandera = true;
        conexionn con = new conexionn();

        if (!user.equals("") || !pass.equals("")) {

            try {
                //llamado de la clase con el metodo de conexion a la db
                Connection cn = con.getconnection();

                //instruccion hacia la db   
//                PreparedStatement pst = cn.prepareStatement("select tipo_nivel, estatus from usuarios where username  = '" + user
//                        + "' and password = '" + pass + "'");
                PreparedStatement pst = cn.prepareStatement("select username, password, estado, permisos from usuarios where username  = '"
                        + user + "' and password = '" + pass + "'");

                //metodo para ejecutar la instruccion a la db
                ResultSet rs = pst.executeQuery();

                //condicion  si se cumple la instruccion a la db
                if (rs.next()) {

                    //variables para guardar lo que encontro la db y que nos lo retorne mediante el metodo getString
                    String estado = rs.getString("estado");
                    String permisos = rs.getString("permisos");

                    //condiciones anidadas referente al tipo de cuenta ingresada
                    if (estado.equalsIgnoreCase("Activo") && permisos.equalsIgnoreCase("Administrador")) {
                        //metodo para destruir la interfaz actual y pasa a la interfaz referente al tipo de nivel
                        this.dispose();
                        //metodo para ir a la interfaz referente al tipo de nivel (en este caso administrador)
                        new PrincipalForm().setVisible(true);

                    } else if (estado.equalsIgnoreCase("Activo") && permisos.equalsIgnoreCase("Funcionario")) {
                        this.dispose();
//                        
//                          new Capturista().setVisible(true);

                        new SecondForm().setVisible(true);
//                        
//                    } else if(tipo_nivel.equalsIgnoreCase("Tecnico") && estatus.equalsIgnoreCase("Activo")){
//                        dispose();
//                        
//                          new Tecnico().setVisible(true);
                    }
                } else if (intentos == 3) {
                    JOptionPane.showMessageDialog(null, "Intentos de acceso excedidos, intentelo mas tarde...");
                    System.exit(0);

                } else {
                    //optionpane para notificar que los datos de ingreso no existen en la db
                    JOptionPane.showMessageDialog(null, "Datos de acceso incorrecto");

                    txt_username.setText("");
                    txt_pass.setText("");
                    intentos = intentos + 1;

//                    bandera = false;
//                        return false;
                }

            } catch (HeadlessException | SQLException e) {
                System.err.println("Error en el botón login" + e);
                JOptionPane.showMessageDialog(null, "¡¡Error al iniciar sesión, contacte al administrador!!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            txt_pass.setEchoChar((char) 0);
        } else {
            txt_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label_fondo_login;
    private javax.swing.JLabel label_icono_login;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
