/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jardinedenhotel.view;

import com.jardinedenhotel.controller.ManageCustomer;
import com.jardinedenhotel.controller.ManageRooms;
import com.jardinedenhotel.controller.ManageUsers;
import com.jardinedenhotel.dao.RoomDAO;
import com.jardinedenhotel.model.Client;
import com.jardinedenhotel.model.Room;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yader Jr
 */
public class ManageRoomsForm extends javax.swing.JFrame {

    ManageRooms manageRooms;

    Room room;
    int fila;

    public static int IDCliente_update = 0;

    DefaultTableModel model = new DefaultTableModel();

    public ManageRoomsForm() throws SQLException {
        initComponents();

        setSize(1050, 650);

        setResizable(false);

        setTitle("Gestión de habitaciones");

        setLocationRelativeTo(null);

        manageRooms = new ManageRooms();

        jTextField_ruta.setVisible(false);

        RoomDAO room_dao_tabla = new RoomDAO();
        room_dao_tabla.tablaHabitaciones(jTable1);

//        manageRooms = new ManageRooms();
//        manageRooms = null;
//        listarHabitaciones();
        //this.setExtendedState(MAXIMIZED_BOTH);
        ImageIcon wallpaper = new ImageIcon("src/img/hotel2.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(label_fondo.getWidth(),
                label_fondo.getHeight(), Image.SCALE_DEFAULT));
        //metodo setIcon para asignarle el wallpaper al label
        label_fondo.setIcon(icono);

        this.repaint();
        
         setIconImage(new ImageIcon(getClass().getResource("/img/logo_hotel.png")).getImage());

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

//        jTable1.addMouseListener(new MouseAdapter() {
////
//            @Override
//            public void mouseClicked(MouseEvent e) {
//
//                int fila_point = jTable1.rowAtPoint(e.getPoint());
//
//                int columna_point = 0;
//
//                int fila = jTable1.getSelectedRow();
//                if (fila != -1) {
//                    txtID.setText("" + client.getIdCliente());
//                    txtNombre.setText("" + client.getNombreCliente());
//                    txtApellidos.setText("" + client.getApellidoCliente());
//                    txtDireccion.setText("" + client.getDireccion());
//                    txtEmpresa.setText("" + client.getEmpresa());
//                    txtCorreo.setText("" + client.getCorreo());
//                    txtTelefono.setText("" + client.getTelefono());
//                    txtID.setEditable(false);
//                }
//        if (fila_point > -1) {
//            IDCliente_update = (int) model.getValueAt(fila_point, columna_point);
//            JOptionPane.showMessageDialog(null, "El id del cliente seleccionado es: " + IDCliente_update);
//
//            InformacionCliente informacion_cliente = new InformacionCliente();
//
//            informacion_cliente.setVisible(true);
//            txtID.setText("" + model.getValueAt(fila_point, 0));
//            txtNombre.setText("" + model.getValueAt(fila_point, 1));
//            txtApellidos.setText("" + model.getValueAt(fila_point, 2));
//            txtDireccion.setText("" + model.getValueAt(fila_point, 3));
//            txtEmpresa.setText("" + model.getValueAt(fila_point, 4));
//            txtCorreo.setText("" + model.getValueAt(fila_point, 5));
//            txtTelefono.setText("" + model.getValueAt(fila_point, 6));
//            txtID.setEditable(false);
////
//                }
//            }
//
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPrecioDia = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel_imagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        cmbEstado = new javax.swing.JComboBox<>();
        SpnHuespedes = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jTextField_ruta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        SpnHuespedes1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        label_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestión habitaciones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripción");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Precio día");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 70, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("<html>Cargar<br>imagen</br></html>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 80, 60, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Adultos");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 20, -1));
        getContentPane().add(txtPrecioDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 70, 30));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 90, 70));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Adultos", "Niños", "Precio día", "Estado", "Imagen"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1050, 190));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regreso.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 90, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 90, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 90, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir5.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 90, 70));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar habitación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Editar habitación");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar habitación");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar habitación");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Imprimir reporte");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/remover.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 90, 70));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Regresar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 240, -1, -1));

        jLabel_imagen.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 190, 120));

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtAreaDescripcion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 200, 80));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre", "Ocupada" }));
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 120, -1));
        getContentPane().add(SpnHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 285, 80, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/subir.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 70, 60));
        getContentPane().add(jTextField_ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 210, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Niños");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 50, -1));
        getContentPane().add(SpnHuespedes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 285, 80, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Estado");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, -1));
        getContentPane().add(label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String mag = validarDatos();
        if (mag.equals("")) {
            try {
                room = new Room();
                room.setId_habitacion(Integer.parseInt(txtID.getText()));
                room.setDescripcion(txtAreaDescripcion.getText());

                File ruta = new File(jTextField_ruta.getText());

                try {

                    byte[] icono = new byte[(int) ruta.length()];
                    InputStream input = new FileInputStream(ruta);
                    input.read(icono);

                    room.setImagen(icono);
                } catch (IOException ex) {
                    room.setImagen(null);
                }

                room.setAdultos((Integer) SpnHuespedes.getValue());
                room.setNinios((Integer) SpnHuespedes1.getValue());
                room.setPrecio_dia(Double.parseDouble(txtPrecioDia.getText()));
                room.setEstado(cmbEstado.getSelectedItem().toString());
//            client.setTelefono(Integer.parseInt(txtTelefono.getText()));

//                if (room_dao.RegistrarHabitacionConFoto(room))
//                {
//
//                    JOptionPane.showMessageDialog(null, "Habitación almacenada exitosamente",
//                            "Guardar", JOptionPane.INFORMATION_MESSAGE);
//                    // this.dispose();
//                    limpiar_campos();
//                    listarHabitaciones();
//
//                } else
//                {
//                    JOptionPane.showMessageDialog(null, mag, "Error validando datos...",
//                            JOptionPane.ERROR_MESSAGE);
//                }
                RoomDAO room_dao = new RoomDAO();
//                room_dao.RegistrarHabitacionConFoto(room);

                ManageRooms manage_rooms = new ManageRooms();
                manage_rooms.insertarRoom(room);
                JOptionPane.showMessageDialog(null, "Habitación ingresada con exito");
                limpiar_campos();
                room_dao.tablaHabitaciones(jTable1);
//                listarHabitaciones();

            } catch (SQLException ex) {
                Logger.getLogger(ManageRoomsForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int _fila = jTable1.getSelectedRow();
        if (fila != -1) {
            int idRoom = Integer.parseInt(jTable1.getValueAt(_fila, 0).toString());
            int resp = JOptionPane.showConfirmDialog(rootPane,
                    "esta seguro de eliminar la habitación ?" + idRoom, "Eliminar",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (resp == JOptionPane.YES_OPTION) {
                manageRooms.conectarBD();
                if (manageRooms.eliminarRoom(idRoom)) {
                    JOptionPane.showMessageDialog(rootPane, "Habitación eliminado exitosamente", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                    limpiar_campos();
                    listarHabitaciones();

                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al eliminar la habitación", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione la habitación que desea eliminar", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String mag = validarDatos();
        if (mag.equals("")) {
            room = new Room();
            room.setId_habitacion(Integer.parseInt(txtID.getText()));
            room.setDescripcion(txtAreaDescripcion.getText());

            File ruta = new File(jTextField_ruta.getText());

            try {

                byte[] icono = new byte[(int) ruta.length()];
                InputStream input = new FileInputStream(ruta);
                input.read(icono);

                room.setImagen(icono);
            } catch (IOException ex) {
                room.setImagen(null);
            }
//            int value = (Integer) SpnHuespedes.getValue();
            room.setAdultos((Integer) SpnHuespedes.getValue());
            room.setNinios((Integer) SpnHuespedes1.getValue());
            room.setPrecio_dia(Integer.parseInt(txtPrecioDia.getText()));
            room.setEstado(String.valueOf(cmbEstado.getSelectedItem()));
//            client.setTelefono(Integer.parseInt(txtTelefono.getText()));

            if (manageRooms.editarRoom(room)) {
                JOptionPane.showMessageDialog(null, "habitación editada exitosamente",
                        "Editar", JOptionPane.INFORMATION_MESSAGE);
//                winCategoria.dispose();
                limpiar_campos();

                listarHabitaciones();
            } else {
                JOptionPane.showMessageDialog(null, "Error al editar habitación", "Editar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
// int fila = jTable1.rowAtPoint(evt.getPoint());
//        int fila_point = jTable1.rowAtPoint(evt.getPoint());
//
//        int columna_point = 0;
//
//        if (fila_point > -1) {
////                    IDCliente_update = (int) model.getValueAt(fila_point, columna_point);
////                    
////                    JOptionPane.showMessageDialog(null, "El id del cliente seleccionado es: "+IDCliente_update);
////                    
////                    InformacionCliente informacion_cliente = new InformacionCliente();
////                    
////                    informacion_cliente.setVisible(true);
//
//            txtID.setText("" + client.getIdCliente());
//            txtNombre.setText("" + client.getNombreCliente());
//            txtApellidos.setText("" + client.getApellidoCliente());
//            txtDireccion.setText("" + client.getDireccion());
//            txtEmpresa.setText("" + client.getEmpresa());
//            txtCorreo.setText("" + client.getCorreo());
//            txtTelefono.setText("" + client.getTelefono());
//            txtID.setEditable(false);
//
//        }
//        int fila = jTable1.getSelectedRow();
//        if (fila > -1) {
//            txtID.setText("" + model.getValueAt(fila, 0).toString());
//            txtNombre.setText("" + model.getValueAt(fila, 1).toString());
//            txtApellidos.setText("" + model.getValueAt(fila, 2).toString());
//            txtDireccion.setText("" + model.getValueAt(fila, 3).toString());
//            txtEmpresa.setText("" + model.getValueAt(fila, 4).toString());
//            txtCorreo.setText("" + model.getValueAt(fila, 5).toString());
//            txtTelefono.setText("" + model.getValueAt(fila, 6).toString());
//            txtID.setEditable(false);
//////            jTable1.getval
//        } else {
//            JOptionPane.showMessageDialog(null, "Error tabla vacia");
//        }

        fila = jTable1.rowAtPoint(evt.getPoint());
        SeleccionarFila(fila);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

//        if (BuscarCliente()) {
//            SeleccionarFila(fila);
//        } else {
//
//            JOptionPane.showMessageDialog(null,
//                    "El ID " + txtID.getText() + " No existe!");
//        }
        String codigo = txtID.getText();
//        boolean encontrado = false;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (codigo.equals(String.valueOf(jTable1.getValueAt(i, 0)))) {
//                encontrado = true;
                fila = i;
                jTable1.changeSelection(i, 1, false, false);
                //  SeleccionarFila(fila);

            } else {
//                JOptionPane.showMessageDialog(null,
//                        "El ID " + txtID.getText() + " No existe!");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("JPG, PNG Y GIF", "jpg", "png", "gif");
        jfc.setFileFilter(fnef);

        String ruta_img = "";

        int opc = jfc.showOpenDialog(this);

        if (opc == JFileChooser.APPROVE_OPTION) {

            ruta_img = jfc.getSelectedFile().getPath();
            jTextField_ruta.setText(ruta_img);
            Image imagen = new ImageIcon(ruta_img).getImage();
            ImageIcon icon = new ImageIcon(imagen.getScaledInstance(jLabel_imagen.getWidth(), jLabel_imagen.getHeight(), Image.SCALE_SMOOTH));
            jLabel_imagen.setIcon(icon);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//        manageRooms.cargarReporteHabitaciones();
manageRooms.reporteIDHabitacion(Integer.parseInt(txtID.getText()));

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoomsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageRoomsForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageRoomsForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnHuespedes;
    private javax.swing.JSpinner SpnHuespedes1;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_ruta;
    private javax.swing.JLabel label_fondo;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrecioDia;
    // End of variables declaration//GEN-END:variables

    private void listarHabitaciones() {
        manageRooms.conectarBD();
        ResultSet rs = manageRooms.listarRooms();
        if (rs != null) {
            jTable1.setModel(manageRooms.cargarEnTabla(rs));
            //lblTotal.setText("Total: " + jTable1.getRowCount());
        }
        manageRooms.desconectarBD();
    }

    private String validarDatos() {
        if (txtID.getText().trim().equals("")) {
            txtID.requestFocus();
            return "Por favor ingrese el ID";
        } else {
            try {
                Integer.parseInt(txtID.getText());
            } catch (NumberFormatException e) {
                txtID.requestFocus();
                return "El ID  debe ser un numero";
            }
        }

//        if (txtNombre.getText().trim().equals("")) {
//            txtNombre.requestFocus();
//            return "Por favor ingrese el nombre de la categoria";
//        }
//
//        if (txtApellidos.getText().trim().equals("")) {
//            txtApellidos.requestFocus();
//            return "Por favor ingrese la descripcion de la categoria";
//        }
//
//        if (txtDireccion.getText().trim().equals("")) {
//            txtDireccion.requestFocus();
//            return "Por favor ingrese la descripcion de la categoria";
//        }
        if (txtPrecioDia.getText().trim().equals("")) {
            txtPrecioDia.requestFocus();
            return "Por favor ingrese la descripcion de la categoria";
        }

//        if (txtCorreo.getText().trim().equals("")) {
//            txtCorreo.requestFocus();
//            return "Por favor ingrese la descripcion de la categoria";
//        }
//
//        if (txtTelefono.getText().trim().equals("")) {
////            txtTelefono.requestFocus();
//            return "Por favor ingrese el numero teléfonico";
//        } else {
//            try {
////                Integer.parseInt(txtTelefono.getText());
//            } catch (NumberFormatException e) {
////                txtTelefono.requestFocus();
//                return "El numero teléfonico debe ser un numero";
//            }
//        }
        return "";

    }

    private void SeleccionarFila(int _Fila) {

        RoomDAO room_dao_clic_tabla = new RoomDAO();

        txtID.setText("" + String.valueOf(jTable1.getValueAt(fila, 0)));

        int ID = (int) (jTable1.getValueAt(fila, 0));

        room_dao_clic_tabla.CargarHabitacion(ID, txtID, txtPrecioDia, txtAreaDescripcion, SpnHuespedes, SpnHuespedes1, jLabel_imagen, cmbEstado);
//        txtAreaDescripcion.setText("" + String.valueOf(jTable1.getValueAt(fila, 1)));
//        jLabel_imagen.setText("" + String.valueOf(jTable1.getValueAt(fila, 2)));
//        SpnHuespedes.setValue("" + String.valueOf(jTable1.getValueAt(fila, 3)));
//        txtPrecioDia.setText("" + String.valueOf(jTable1.getValueAt(fila, 4)));
//        cmbEstado.setSelectedItem("" + String.valueOf(jTable1.getValueAt(fila, 5)));
//        txtTelefono.setText("" + String.valueOf(jTable1.getValueAt(fila, 6)));
        txtID.setEditable(false);

//        jTextField_codigo_planta.setText(String.valueOf(TablaDatos.getValueAt(fila, 0)));
//        jTextField_nombre_planta.setText(String.valueOf(TablaDatos.getValueAt(fila, 1)));
//        jTextField_tipo_planta.setText(String.valueOf(TablaDatos.getValueAt(fila, 2)));
//        jTextField_tiempo_crecimiento.setText(String.valueOf(TablaDatos.getValueAt(fila, 3)));
    }

    private boolean BuscarCliente() {
        String codigo = txtID.getText();
        boolean encontrado = false;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (codigo.equals(jTable1.getValueAt(i, 0))) {
                encontrado = true;
                fila = i;
                jTable1.changeSelection(i, 1, false, false);
            }
        }
        return encontrado;
    }

    public void limpiar_campos() {
        txtID.setText("");
//        txtNombre.setText("");
//        txtApellidos.setText("");
//        txtDireccion.setText("");
//        txtPrecioDia.setText("");
//        txtCorreo.setText("");
//        txtTelefono.setText("");
        txtID.setEditable(true);

    }

    //    public void llenar_cmb_categoria() throws SQLException {
//
//        GestionCategoria ob1 = new GestionCategoria();
//        ArrayList<Categoria> Listar_categorias = ob1.get_categorias();
//
//        cboCategoria.removeAllItems();
//
//        cboCategoria.addItem("Seleccione la categoria: ");
//
//        for (int i = 0; i < Listar_categorias.size(); i++)
//        {
//            cboCategoria.addItem(String.valueOf(Listar_categorias.get(i).getIdCategoria()));
//        }
//    }
}
